apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace: {{ .Release.Namespace }}
data:
  MYSQL_HOST: {{ .Values.config.mysqlHost }}
  MYSQL_PORT: {{ .Values.config.mysqlPort | quote }}
  MYSQL_DATABASE: {{ .Values.config.mysqlDatabase }}
  OLLAMA_URL: {{ .Values.config.ollamaUrl }}