apiVersion: v1
kind: Secret
metadata:
  name: bankapp-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysqlRootPassword | b64enc }}
  MYSQL_USER: {{ .Values.secret.mysqlUser | b64enc }}
  MYSQL_PASSWORD: {{ .Values.secret.mysqlPassword | b64enc }}